name: "Discard-old-logs"
description: "Find all jobs that run for this branch, and discard them"
author: "Miklos Gergely"
inputs:
  url:
    description: "Jenkins URL including http/https protocol"
    required: true
  job_name:
    description: "Jenkins job name to query"
    required: true
  username:
    description: "Jenkins username"
    required: true
  api_token:
    description: "Jenkins API token"
    required: true
  access_token:
    description: "GitHub token"
    required: false
runs:
  using: "docker"
  image: "../discard_old_builds.Dockerfile"
