name: "MergeBranch"
description: "Create a merge branch and PR from two branches"
author: "Miklos Gergely"
inputs:
  access_token:
    description: "GitHub token"
    required: true
  head_branch:
    description: "branch with your changes"
    required: false
  target_branch:
    description: "branch to send your changes to"
    required: false
  repository_name:
    description: "full name of the repo e.g.: intland/cbdev-git"
    required: false
runs:
  using: "docker"
  image: "../merge_branch.Dockerfile"
