name: "PMD"
description: "Collect file line changes for PMD"
author: "Sandor Zelei"
inputs:
  access_token:
    description: "GitHub token"
    required: true
runs:
  using: "docker"
  image: "../pmd.Dockerfile"
